apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: nginxproxies.gateway.nginx.org
spec:
  group: gateway.nginx.org
  names:
    kind: NginxProxy
    listKind: NginxProxyList
    plural: nginxproxies
    singular: nginxproxy
    categories:
      - nginx-gateway-fabric
  scope: Namespaced
  versions:
    - name: v1alpha2
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
