---
# ArgoCD OIDC credentials from Authentik
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-oidc-config
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-store
    kind: ClusterSecretStore
  target:
    name: argocd-oidc-config
    creationPolicy: Owner
  data:
    - secretKey: client-id
      remoteRef:
        key: authentik-argocd-oidc
        property: client-id
    - secretKey: client-secret
      remoteRef:
        key: authentik-argocd-oidc
        property: client-secret
