apiVersion: platform.kratix.io/v1alpha1
kind: Promise
metadata:
  name: argocd-application
  labels:
    kratix.io/promise-type: platform
spec:
  destinationSelectors:
    - matchLabels:
        capability.vcluster: "true"

  api:
    apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      name: argocdapplications.platform.integratn.tech
    spec:
      group: platform.integratn.tech
      scope: Namespaced
      names:
        plural: argocdapplications
        singular: argocdapplication
        kind: ArgoCDApplication
      versions:
        - name: v1alpha1
          served: true
          storage: true
          schema:
            openAPIV3Schema:
              type: object
              properties:
                spec:
                  type: object
                  required:
                    - name
                    - namespace
                    - project
                    - source
                    - destination
                  properties:
                    name:
                      type: string
                    namespace:
                      type: string
                    annotations:
                      type: object
                      additionalProperties:
                        type: string
                    labels:
                      type: object
                      additionalProperties:
                        type: string
                    finalizers:
                      type: array
                      items:
                        type: string
                    project:
                      type: string
                    source:
                      type: object
                      required:
                        - repoURL
                        - chart
                        - targetRevision
                      properties:
                        repoURL:
                          type: string
                        chart:
                          type: string
                        targetRevision:
                          type: string
                        helm:
                          type: object
                          properties:
                            releaseName:
                              type: string
                            valuesObject:
                              type: object
                              x-kubernetes-preserve-unknown-fields: true
                    destination:
                      type: object
                      required:
                        - server
                        - namespace
                      properties:
                        server:
                          type: string
                        namespace:
                          type: string
                    syncPolicy:
                      type: object
                      x-kubernetes-preserve-unknown-fields: true
                status:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true

  workflows:
    resource:
      configure:
        - apiVersion: platform.kratix.io/v1alpha1
          kind: Pipeline
          metadata:
            name: argocd-application-configure
            namespace: platform-requests
          spec:
            containers:
              - name: render
                image: ghcr.io/jamesatintegratnio/argocd-application-promise-pipeline:main
                imagePullPolicy: Always
      delete:
        - apiVersion: platform.kratix.io/v1alpha1
          kind: Pipeline
          metadata:
            name: argocd-application-delete
            namespace: platform-requests
          spec:
            containers:
              - name: delete
                image: ghcr.io/jamesatintegratnio/argocd-application-promise-pipeline:main
                imagePullPolicy: Always
                command: ["/scripts/delete-pipeline.sh"]
