apiVersion: platform.kratix.io/v1alpha1
kind: Promise
metadata:
  name: argocd-application
  labels:
    kratix.io/promise-type: platform
spec:
  destinationSelectors:
    - matchLabels:
        capability.vcluster: "true"

  api:
    apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      name: argocdapplications.platform.integratn.tech
    spec:
      group: platform.integratn.tech
      scope: Namespaced
      names:
        plural: argocdapplications
        singular: argocdapplication
        kind: ArgoCDApplication
      versions:
        - name: v1alpha1
          served: true
          storage: true
          schema:
            openAPIV3Schema:
              type: object
              properties:
                spec:
                  type: object
                  required:
                    - name
                    - namespace
                    - project
                    - source
                    - destination
                  properties:
                    name:
                      type: string
                      description: Name of the ArgoCD Application
                      pattern: '^[a-z0-9]([-a-z0-9]*[a-z0-9])?$'
                      maxLength: 63
                    namespace:
                      type: string
                      description: Namespace where the Application will be created (typically argocd)
                      default: argocd
                    annotations:
                      type: object
                      description: Annotations to apply to the Application
                      additionalProperties:
                        type: string
                    labels:
                      type: object
                      description: Labels to apply to the Application
                      additionalProperties:
                        type: string
                    finalizers:
                      type: array
                      description: Finalizers to apply to the Application
                      items:
                        type: string
                    project:
                      type: string
                      description: ArgoCD AppProject this Application belongs to
                    source:
                      type: object
                      description: Source configuration for the Application
                      required:
                        - repoURL
                        - targetRevision
                      properties:
                        repoURL:
                          type: string
                        chart:
                          type: string
                        targetRevision:
                          type: string
                        helm:
                          type: object
                          properties:
                            releaseName:
                              type: string
                            valuesObject:
                              type: object
                              x-kubernetes-preserve-unknown-fields: true
                    destination:
                      type: object
                      description: Deployment destination
                      required:
                        - server
                        - namespace
                      properties:
                        server:
                          type: string
                        namespace:
                          type: string
                    syncPolicy:
                      type: object
                      description: ArgoCD sync policy settings
                      x-kubernetes-preserve-unknown-fields: true
                status:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true

  workflows:
    resource:
      configure:
        - apiVersion: platform.kratix.io/v1alpha1
          kind: Pipeline
          metadata:
            name: argocd-app-configure
          spec:
            containers:
              - name: configure
                image: ghcr.io/jamesatintegratnio/argocd-application-configure:latest
                imagePullPolicy: Always
                securityContext:
                  allowPrivilegeEscalation: false
                  readOnlyRootFilesystem: true
                  runAsNonRoot: true
                  runAsUser: 65532
                  capabilities:
                    drop: ["ALL"]
                  seccompProfile:
                    type: RuntimeDefault
      delete:
        - apiVersion: platform.kratix.io/v1alpha1
          kind: Pipeline
          metadata:
            name: argocd-app-delete
          spec:
            containers:
              - name: delete
                image: ghcr.io/jamesatintegratnio/argocd-application-configure:latest
                imagePullPolicy: Always
                securityContext:
                  allowPrivilegeEscalation: false
                  readOnlyRootFilesystem: true
                  runAsNonRoot: true
                  runAsUser: 65532
                  capabilities:
                    drop: ["ALL"]
                  seccompProfile:
                    type: RuntimeDefault
