---
# Grafana OAuth2/OIDC credentials from Authentik
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-oidc-config
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-store
    kind: ClusterSecretStore
  target:
    name: grafana-oidc-config
    creationPolicy: Owner
  data:
    - secretKey: client-id
      remoteRef:
        key: authentik-grafana-oidc
        property: client-id
    - secretKey: client-secret
      remoteRef:
        key: authentik-grafana-oidc
        property: client-secret
