apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: platform-status-reconciler
  labels:
    app.kubernetes.io/name: platform-status-reconciler
    app.kubernetes.io/part-of: platform
rules:
  # Read VClusterOrchestratorV2 resources
  - apiGroups: ["platform.integratn.tech"]
    resources: ["vclusterorchestratorv2s"]
    verbs: ["get", "list", "watch"]
  # Patch status subresource
  - apiGroups: ["platform.integratn.tech"]
    resources: ["vclusterorchestratorv2s/status"]
    verbs: ["patch", "update"]
  # Read ArgoCD Applications
  - apiGroups: ["argoproj.io"]
    resources: ["applications"]
    verbs: ["get", "list"]
  # Read pods + secrets (for readiness + kubeconfig check)
  - apiGroups: [""]
    resources: ["pods", "secrets"]
    verbs: ["get", "list"]
  # Read Kratix Work/WorkPlacement
  - apiGroups: ["platform.kratix.io"]
    resources: ["works", "workplacements"]
    verbs: ["get", "list"]
