apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: platform-status-reconciler
  namespace: platform-status-reconciler
  labels:
    app.kubernetes.io/name: platform-status-reconciler
    app.kubernetes.io/part-of: platform
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: platform-status-reconciler
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
