apiVersion: v1
kind: ServiceAccount
metadata:
  name: platform-status-reconciler
  namespace: platform-status-reconciler
  labels:
    app.kubernetes.io/name: platform-status-reconciler
    app.kubernetes.io/part-of: platform
