apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: demo-legacy-secret
  namespace: demo
spec:
  dataFrom:
  - extract:
      key: demo/legacy
      property: credentials
      version: "3"
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-store
  target:
    name: demo-legacy-secret
