apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kratix-github-credentials
  namespace: kratix-platform-system
spec:
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  target:
    name: kratix-github-credentials
    creationPolicy: Owner
  data:
    - secretKey: appID
      remoteRef:
        key: kratix-gitops-statestore
        property: AppID
    - secretKey: installationID
      remoteRef:
        key: kratix-gitops-statestore
        property: InstallID
    - secretKey: privateKey
      remoteRef:
        key: kratix-gitops-statestore
        property: PrivateKey
