apiVersion: platform.kratix.io/v1alpha1
kind: Promise
metadata:
  name: vcluster
  labels:
    kratix.io/promise-type: platform
spec:
  destinationSelectors:
    - matchLabels:
        capability.vcluster: "true"
  
  api:
    apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      name: vclusters.platform.integratn.tech
    spec:
      group: platform.integratn.tech
      scope: Namespaced
      names:
        plural: vclusters
        singular: vcluster
        kind: VCluster
      versions:
        - name: v1alpha1
          served: true
          storage: true
          schema:
            openAPIV3Schema:
              type: object
              properties:
                spec:
                  type: object
                  required:
                    - name
                  properties:
                    name:
                      type: string
                      description: Name of the vcluster instance
                      pattern: '^[a-z0-9]([-a-z0-9]*[a-z0-9])?$'
                      maxLength: 63
                    k8sVersion:
                      type: string
                      description: Kubernetes version for the virtual cluster
                      default: "1.34"
                      enum:
                        - "1.34"
                        - "1.33"
                        - "1.32"
                    isolationMode:
                      type: string
                      description: Workload isolation mode
                      default: "standard"
                      enum:
                        - "standard"
                        - "strict"
                    resources:
                      type: object
                      description: Resource requests and limits for the vcluster control plane
                      properties:
                        requests:
                          type: object
                          properties:
                            cpu:
                              type: string
                              default: "200m"
                            memory:
                              type: string
                              default: "512Mi"
                        limits:
                          type: object
                          properties:
                            cpu:
                              type: string
                              default: "1000m"
                            memory:
                              type: string
                              default: "1Gi"
                status:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
  
  workflows:
    resource:
      configure:
        - apiVersion: platform.kratix.io/v1alpha1
          kind: Pipeline
          metadata:
            name: resource-configure
            namespace: default
          spec:
            containers:
              - name: generate-vcluster-resources
                image: ghcr.io/jamesatintegratnio/vcluster-promise-pipeline:latest
                imagePullPolicy: Always
      delete:
        - apiVersion: platform.kratix.io/v1alpha1
          kind: Pipeline
          metadata:
            name: resource-delete
            namespace: default
          spec:
            containers:
              - name: delete-vcluster-resources
                image: ghcr.io/jamesatintegratnio/vcluster-promise-pipeline:latest
                imagePullPolicy: Always
                command: ["/scripts/delete-pipeline.sh"]
