# NetworkPolicies for ai namespace (RAG platform stack)
---
# Create namespace so default-deny exists before app sync
apiVersion: v1
kind: Namespace
metadata:
  name: ai
---
# Allow DNS resolution
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-dns
  namespace: ai
spec:
  podSelector: {}
  policyTypes:
    - Egress
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
---
# Allow kube-apiserver access (ExternalSecrets, service discovery)
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-kube-api
  namespace: ai
spec:
  endpointSelector: {}
  egress:
    - toEntities:
        - kube-apiserver
---
# Allow intra-namespace communication (Open WebUI <-> Qdrant, Pipelines <-> Qdrant, etc.)
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-intra-namespace
  namespace: ai
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ai
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ai
---
# Allow egress to external Ollama (10.0.3.4:11434)
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-ollama-egress
  namespace: ai
spec:
  podSelector: {}
  policyTypes:
    - Egress
  egress:
    - to:
        - ipBlock:
            cidr: 10.0.3.4/32
      ports:
        - protocol: TCP
          port: 11434
---
# Allow egress to GitHub (HTTPS for git clone in indexer)
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-github-egress
  namespace: ai
spec:
  podSelector:
    matchLabels:
      app: git-indexer
  policyTypes:
    - Egress
  egress:
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
            except:
              - 10.0.0.0/8
              - 172.16.0.0/12
              - 192.168.0.0/16
      ports:
        - protocol: TCP
          port: 443
---
# Allow egress to NFS server (for PVC mounts)
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-nfs-egress
  namespace: ai
spec:
  podSelector: {}
  policyTypes:
    - Egress
  egress:
    - to:
        - ipBlock:
            cidr: 10.0.0.12/32
      ports:
        - protocol: TCP
          port: 2049
        - protocol: UDP
          port: 2049
---
# Allow ingress from nginx-gateway (for Open WebUI HTTPRoute)
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-gateway-ingress
  namespace: ai
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: open-webui
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: nginx-gateway
      ports:
        - protocol: TCP
          port: 8080
---
# Allow egress to nginx-gateway service (for OIDC/OAuth2 to Authentik via auth.cluster.integratn.tech)
# Must use CiliumNetworkPolicy toServices because K8s NetworkPolicy can't match service IPs —
# Cilium evaluates egress policies before DNAT, so namespace selectors and ipBlock rules
# don't match when traffic is sent to ClusterIP or LoadBalancer virtual IPs.
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-authentik-egress
  namespace: ai
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: open-webui
  egress:
    - toServices:
        - k8sService:
            serviceName: nginx-gateway-nginx
            namespace: nginx-gateway
      toPorts:
        - ports:
            - port: "443"
---
# Allow Prometheus scraping from monitoring namespace
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-monitoring-ingress
  namespace: ai
spec:
  podSelector: {}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: monitoring
