# argocd: GitOps platform — server, application-controller, repo-server, redis, notifications, applicationset
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all
  namespace: argocd
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-dns
  namespace: argocd
spec:
  podSelector: {}
  policyTypes:
    - Egress
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-kube-api
  namespace: argocd
spec:
  endpointSelector: {}
  egress:
    - toEntities:
        - kube-apiserver
---
# ArgoCD Server: UI/API, ingress from nginx-gateway
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-argocd-server
  namespace: argocd
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: server
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # External access via nginx-gateway
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: nginx-gateway
      ports:
        - protocol: TCP
          port: 8080
        - protocol: TCP
          port: 8083
    # Prometheus metrics scraping
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: monitoring
      ports:
        - protocol: TCP
          port: 8083
  egress:
    # Internal: repo-server, redis, dex
    - to:
        - podSelector: {}
      ports:
        - protocol: TCP
          port: 8081
        - protocol: TCP
          port: 6379
        - protocol: TCP
          port: 5556
---
# ArgoCD Server: OIDC provider access via gateway LB (Cilium-native for MetalLB VIPs)
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-argocd-server-oidc
  namespace: argocd
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/component: server
  egress:
    - toCIDR:
        - 10.0.4.205/32
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
---
# Application Controller: reconciles desired vs live state
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-application-controller
  namespace: argocd
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: application-controller
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # Prometheus metrics scraping
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: monitoring
      ports:
        - protocol: TCP
          port: 8082
  egress:
    # Internal: repo-server, redis
    - to:
        - podSelector: {}
      ports:
        - protocol: TCP
          port: 8081
        - protocol: TCP
          port: 6379
    # Cluster resources — needs wide access to managed namespaces
    - to:
        - ipBlock:
            cidr: 10.244.0.0/16
      ports:
        - protocol: TCP
          port: 8443
        - protocol: TCP
          port: 443
    # vCluster API endpoints via MetalLB gateway LB (10.0.4.200-253)
    - to:
        - ipBlock:
            cidr: 10.0.4.192/26
      ports:
        - protocol: TCP
          port: 443
---
# Repo Server: clones git repos, renders manifests
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-repo-server
  namespace: argocd
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: repo-server
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # Server + controller fetch rendered manifests
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/component: server
        - podSelector:
            matchLabels:
              app.kubernetes.io/component: application-controller
        - podSelector:
            matchLabels:
              app.kubernetes.io/component: applicationset-controller
      ports:
        - protocol: TCP
          port: 8081
    # Prometheus metrics
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: monitoring
      ports:
        - protocol: TCP
          port: 8084
  egress:
    # Internal: Redis (manifest cache)
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/component: redis
      ports:
        - protocol: TCP
          port: 6379
    # Clone from GitHub / Helm chart repos (external)
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
            except:
              - 10.0.0.0/8
              - 172.16.0.0/12
              - 192.168.0.0/16
      ports:
        - protocol: TCP
          port: 443
        - protocol: TCP
          port: 22
        - protocol: TCP
          port: 80
---
# Redis: in-memory cache for ArgoCD
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-redis
  namespace: argocd
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: redis
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # ArgoCD components connect to Redis
    - from:
        - podSelector: {}
      ports:
        - protocol: TCP
          port: 6379
    # Prometheus metrics
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: monitoring
      ports:
        - protocol: TCP
          port: 9121
  egress: []
---
# Notifications Controller: sends alerts to Matrix
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-notifications-controller
  namespace: argocd
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: notifications-controller
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # Prometheus metrics
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: monitoring
      ports:
        - protocol: TCP
          port: 9001
  egress:
    # Internal: redis
    - to:
        - podSelector: {}
      ports:
        - protocol: TCP
          port: 6379
    # Alertmanager webhook for notifications
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: monitoring
      ports:
        - protocol: TCP
          port: 9093
---
# ApplicationSet Controller
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-applicationset-controller
  namespace: argocd
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: applicationset-controller
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # Webhook receiver + metrics
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: monitoring
      ports:
        - protocol: TCP
          port: 8080
    - from:
        - podSelector: {}
      ports:
        - protocol: TCP
          port: 7000
  egress:
    # Internal: repo-server, server
    - to:
        - podSelector: {}
      ports:
        - protocol: TCP
          port: 8081
        - protocol: TCP
          port: 8080
    # GitHub API for generators
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
            except:
              - 10.0.0.0/8
              - 172.16.0.0/12
              - 192.168.0.0/16
      ports:
        - protocol: TCP
          port: 443
