# kube-system: CoreDNS, Cilium, metrics-server
# Talos manages kube-apiserver, kube-controller-manager, kube-scheduler as static pods
# on the host network — they are NOT affected by NetworkPolicies
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all
  namespace: kube-system
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
---
# CoreDNS must accept DNS queries from ALL pods in the cluster
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-dns-server
  namespace: kube-system
spec:
  podSelector:
    matchLabels:
      k8s-app: kube-dns
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # Accept DNS from all namespaces
    - from:
        - namespaceSelector: {}
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
  egress:
    # Upstream DNS (if CoreDNS forwards externally)
    - ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    # K8s API for service discovery
    - to:
        - ipBlock:
            cidr: 10.0.4.0/24  # API server nodes (Cilium translates ClusterIP before policy eval)
      ports:
        - protocol: TCP
          port: 6443
    # CoreDNS metrics (self, prometheus scraping)
    - to:
        - podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: TCP
          port: 9153
---
# Cilium agent needs broad network access for CNI + kube-proxy replacement
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-cilium-agent
  namespace: kube-system
spec:
  podSelector:
    matchLabels:
      k8s-app: cilium
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # Health checks and Hubble peering from other Cilium agents
    - from:
        - podSelector:
            matchLabels:
              k8s-app: cilium
      ports:
        - protocol: TCP
          port: 4244
    # Prometheus scraping
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: monitoring
      ports:
        - protocol: TCP
          port: 9962
        - protocol: TCP
          port: 9963
        - protocol: TCP
          port: 9964
  egress:
    # Cilium needs broad egress for CNI duties
    # K8s API
    - to:
        - ipBlock:
            cidr: 10.0.4.0/24  # API server nodes (Cilium translates ClusterIP before policy eval)
      ports:
        - protocol: TCP
          port: 6443
    # Node network (health checks, VXLAN/Geneve tunneling)
    - to:
        - ipBlock:
            cidr: 10.0.4.0/24
    # Pod CIDR
    - to:
        - ipBlock:
            cidr: 10.244.0.0/16
    # DNS
    - to:
        - podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
---
# Cilium operator needs K8s API access
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-cilium-operator
  namespace: kube-system
spec:
  podSelector:
    matchLabels:
      io.cilium/app: operator
      name: cilium-operator
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # Prometheus scraping
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: monitoring
      ports:
        - protocol: TCP
          port: 9963
  egress:
    # K8s API
    - to:
        - ipBlock:
            cidr: 10.0.4.0/24  # API server nodes (Cilium translates ClusterIP before policy eval)
      ports:
        - protocol: TCP
          port: 6443
    # DNS
    - to:
        - podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
---
# Hubble Relay needs access to Cilium agents and K8s API
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-hubble-relay
  namespace: kube-system
spec:
  podSelector:
    matchLabels:
      k8s-app: hubble-relay
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # Hubble UI connects to relay
    - from:
        - podSelector:
            matchLabels:
              k8s-app: hubble-ui
      ports:
        - protocol: TCP
          port: 4245
    # Prometheus scraping
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: monitoring
      ports:
        - protocol: TCP
          port: 9966
  egress:
    # Connect to Cilium agent Hubble server on each node
    - to:
        - podSelector:
            matchLabels:
              k8s-app: cilium
      ports:
        - protocol: TCP
          port: 4244
    # K8s API
    - to:
        - ipBlock:
            cidr: 10.0.4.0/24  # API server nodes (Cilium translates ClusterIP before policy eval)
      ports:
        - protocol: TCP
          port: 6443
    # DNS
    - to:
        - podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
---
# Hubble UI needs access to Hubble Relay
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-hubble-ui
  namespace: kube-system
spec:
  podSelector:
    matchLabels:
      k8s-app: hubble-ui
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # Allow access to the UI (via gateway/ingress)
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: nginx-gateway
      ports:
        - protocol: TCP
          port: 8081
  egress:
    # Hubble Relay
    - to:
        - podSelector:
            matchLabels:
              k8s-app: hubble-relay
      ports:
        - protocol: TCP
          port: 4245
    # K8s API (for UI backend)
    - to:
        - ipBlock:
            cidr: 10.0.4.0/24  # API server nodes (Cilium translates ClusterIP before policy eval)
      ports:
        - protocol: TCP
          port: 6443
    # DNS
    - to:
        - podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
