apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-dns
  namespace: loki
spec:
  podSelector: {}
  policyTypes:
    - Egress
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-kube-api
  namespace: loki
spec:
  endpointSelector: {}
  egress:
    - toEntities:
        - kube-apiserver
---
# Loki gateway: receives logs from promtail, queries from Grafana
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-loki-gateway
  namespace: loki
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: gateway
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # Promtail pushes logs
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: promtail
      ports:
        - protocol: TCP
          port: 80
        - protocol: TCP
          port: 8080
    # Loki canary pushes test logs
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/component: canary
      ports:
        - protocol: TCP
          port: 80
        - protocol: TCP
          port: 8080
    # Grafana queries logs
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: monitoring
      ports:
        - protocol: TCP
          port: 80
        - protocol: TCP
          port: 8080
    # nginx-gateway for external UI
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: nginx-gateway
      ports:
        - protocol: TCP
          port: 80
        - protocol: TCP
          port: 8080
    # AI pipelines pod queries (LogQL via RAG pipeline)
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ai
          podSelector:
            matchLabels:
              app.kubernetes.io/name: pipelines
      ports:
        - protocol: TCP
          port: 80
        - protocol: TCP
          port: 8080
  egress:
    # Forward to Loki backend pods (same namespace)
    - to:
        - podSelector: {}
      ports:
        - protocol: TCP
          port: 3100
        - protocol: TCP
          port: 8080
        - protocol: TCP
          port: 9095
        - protocol: TCP
          port: 7946
---
# Loki canary: pushes test logs to loki-gateway and reads them back
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-loki-canary
  namespace: loki
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: canary
  policyTypes:
    - Egress
  egress:
    # Push logs to loki-gateway
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/component: gateway
      ports:
        - protocol: TCP
          port: 8080
        - protocol: TCP
          port: 80
---
# Loki backend: storage, compactor, ingester, querier
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-loki-backend
  namespace: loki
spec:
  podSelector:
    matchExpressions:
      - key: app.kubernetes.io/component
        operator: NotIn
        values:
          - gateway
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # Gateway and canary push logs + inter-component communication
    - from:
        - podSelector: {}
      ports:
        - protocol: TCP
          port: 3100
        - protocol: TCP
          port: 9095
        - protocol: TCP
          port: 7946
        - protocol: TCP
          port: 11211
    # Prometheus scrapes Loki and memcached-exporter metrics
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: monitoring
      ports:
        - protocol: TCP
          port: 3100
        - protocol: TCP
          port: 9150
  egress:
    # Inter-component communication + memcached (same namespace)
    - to:
        - podSelector: {}
      ports:
        - protocol: TCP
          port: 3100
        - protocol: TCP
          port: 9095
        - protocol: TCP
          port: 7946
        - protocol: TCP
          port: 11211
    # NFS storage backend (if using filesystem storage)
    - to:
        - ipBlock:
            cidr: 10.0.0.0/8
      ports:
        - protocol: TCP
          port: 2049