# nginx-gateway: nginx-gateway-fabric (control plane) + nginx (data plane)
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all
  namespace: nginx-gateway
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-dns
  namespace: nginx-gateway
spec:
  podSelector: {}
  policyTypes:
    - Egress
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-kube-api
  namespace: nginx-gateway
spec:
  endpointSelector: {}
  egress:
    - toEntities:
        - kube-apiserver
---
# nginx data plane: accepts external traffic, forwards to backend services
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-nginx-dataplane
  namespace: nginx-gateway
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: nginx-gateway-nginx
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # External traffic via MetalLB LoadBalancer
    - ports:
        - protocol: TCP
          port: 80
        - protocol: TCP
          port: 443
    # Prometheus metrics scraping
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: monitoring
      ports:
        - protocol: TCP
          port: 9113
  egress:
    # Backend services in all namespaces — WIDE egress needed
    # ArgoCD server
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: argocd
      ports:
        - protocol: TCP
          port: 8080
    # Grafana
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: monitoring
      ports:
        - protocol: TCP
          port: 3000
        - protocol: TCP
          port: 9090
    # Loki gateway
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: loki
      ports:
        - protocol: TCP
          port: 80
        - protocol: TCP
          port: 8080
    # Alertmanager
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: monitoring
      ports:
        - protocol: TCP
          port: 9093
    # Prometheus
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: monitoring
      ports:
        - protocol: TCP
          port: 9090
    # Hubble UI
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: hubble-ui
      ports:
        - protocol: TCP
          port: 8081
    # Trivy Operator Explorer
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: trivy-system
          podSelector:
            matchLabels:
              app.kubernetes.io/name: trivy-operator-explorer
      ports:
        - protocol: TCP
          port: 8080
    # Authentik SSO
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: authentik
          podSelector:
            matchLabels:
              app.kubernetes.io/name: authentik
              app.kubernetes.io/component: server
      ports:
        - protocol: TCP
          port: 9443
        - protocol: TCP
          port: 9000
    # vCluster namespaces: route traffic to workloads in any vcluster
    - to:
        - namespaceSelector:
            matchLabels:
              platform.integratn.tech/type: vcluster
    # Goldilocks dashboard
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: goldilocks
          podSelector:
            matchLabels:
              app.kubernetes.io/component: dashboard
              app.kubernetes.io/name: goldilocks
      ports:
        - protocol: TCP
          port: 8080
    # Control plane pod for config reload (pod listens on 8443, service maps 443→8443)
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: nginx-gateway-fabric
      ports:
        - protocol: TCP
          port: 443
        - protocol: TCP
          port: 8443
---
# nginx-gateway-fabric control plane: watches Gateway API resources, configures nginx
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-nginx-controlplane
  namespace: nginx-gateway
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: nginx-gateway-fabric
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # Data plane requests config (pod listens on 8443, service maps 443→8443)
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: nginx-gateway-nginx
      ports:
        - protocol: TCP
          port: 443
        - protocol: TCP
          port: 8443
    # Prometheus metrics scraping
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: monitoring
      ports:
        - protocol: TCP
          port: 9113
  egress:
    # Push config to data plane
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: nginx-gateway-nginx
      ports:
        - protocol: TCP
          port: 443
