# ExternalSecret for GitHub MCP personal access token
# Requires 1Password item "github-mcp-pat" with property "token"
# Create a GitHub PAT with: repo, read:org, read:packages scopes
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: eso-github-mcp-secrets
  namespace: ai
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-store
  target:
    name: github-mcp-secrets
    creationPolicy: Owner
  data:
    - secretKey: personal-access-token
      remoteRef:
        key: github-mcp-pat
        property: token
