apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: eso-open-webui-secrets
  namespace: ai
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-store
  target:
    name: open-webui-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: open-webui-secrets
        decodingStrategy: None
        conversionStrategy: Default
        metadataPolicy: None
