# ExternalSecret for MCPO API key (used by Open WebUI to authenticate to MCPO)
# Requires 1Password item "mcpo-api-key" with property "api-key"
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: eso-mcpo-secrets
  namespace: ai
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-store
  target:
    name: mcpo-secrets
    creationPolicy: Owner
  data:
    - secretKey: api-key
      remoteRef:
        key: mcpo-api-key
        property: api-key
