apiVersion: platform.kratix.io/v1alpha1
kind: Promise
metadata:
  name: vcluster-kubeconfig-external-secret
  labels:
    kratix.io/promise-type: platform
spec:
  destinationSelectors:
    - matchLabels:
        capability.vcluster: "true"

  api:
    apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      name: vclusterkubeconfigexternalsecret.platform.integratn.tech
    spec:
      group: platform.integratn.tech
      scope: Namespaced
      names:
        plural: vclusterkubeconfigexternalsecret
        singular: vclusterkubeconfigexternalsecret
        kind: VClusterKubeconfigExternalSecret
      versions:
        - name: v1alpha1
          served: true
          storage: true
          schema:
            openAPIV3Schema:
              type: object
              properties:
                spec:
                  type: object
                  required:
                    - name
                    - targetNamespace
                    - onepasswordItem
                  properties:
                    name:
                      type: string
                    targetNamespace:
                      type: string
                    onepasswordItem:
                      type: string
                status:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true

  workflows:
    resource:
      configure:
        - apiVersion: platform.kratix.io/v1alpha1
          kind: Pipeline
          metadata:
            name: vkes
            namespace: platform-requests
          spec:
            containers:
              - name: render
                image: ghcr.io/jamesatintegratnio/vcluster-kubeconfig-external-secret-promise-pipeline:main
                imagePullPolicy: Always
      delete:
        - apiVersion: platform.kratix.io/v1alpha1
          kind: Pipeline
          metadata:
            name: vkesd
            namespace: platform-requests
          spec:
            containers:
              - name: delete
                image: ghcr.io/jamesatintegratnio/vcluster-kubeconfig-external-secret-promise-pipeline:main
                imagePullPolicy: Always
                command: ["/scripts/delete-pipeline.sh"]
