apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: appteam-global
  namespace: argocd
spec:
  description: Global defaults for app team projects
  sourceRepos:
    - '*'
  destinations:
    - name: '*'
      namespace: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
