apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kratix-git-storage
  namespace: kratix-platform-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: "" # Adjust based on cluster storage class
