apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarr-media-pv
  labels:
    app: sonarr
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  nfs:
    path: /mnt/user/data
    server: 10.0.0.12
  persistentVolumeReclaimPolicy: Retain
  storageClassName: data-nfs-client
  volumeMode: Filesystem
  claimRef:
    namespace: vcluster-media
    name: sonarr-media-pvc-x-media-x-media
