apiVersion: platform.integratn.tech/v1alpha1
kind: HTTPService
metadata:
  name: hello-world
  namespace: platform-requests
spec:
  name: hello-world
  team: platform
  image:
    repository: docker.io/nginxinc/nginx-unprivileged
    tag: latest
  port: 8080
  replicas: 1
  ingress:
    enabled: true
  healthCheck:
    path: /
    port: 8080
