apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mcp-system-app
  namespace: argocd
spec:
  project: platform-services
  source:
    repoURL: https://github.com/jamesatintegratnio/gitops_homelab_2_0
    targetRevision: main
    path: addons/cluster-roles/control-plane/addons/mcp-system
  destination:
    server: https://kubernetes.default.svc
    namespace: mcp-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
