---
apiVersion: platform.integratn.tech/v1alpha1
kind: VCluster
metadata:
  annotations:
    platform.integratn.tech/reconcile-at: "2026-01-19T21:10:00Z"
  name: custom-test
  namespace: platform-requests
spec:
  name: custom-test
  projectName: vcluster-custom-test
  targetNamespace: vcluster-custom-test
  integrations:
    argocd:
      environment: development
      clusterLabels:
        enable_argocd: "true"
        enable_cert_manager: "true"
        enable_ingress_nginx: "true"
        enable_external_secrets: "true"
        enable_metrics_server: "true"
      clusterAnnotations:
        reconcile-token: "20260119211000"
  preset: dev
  coredns:
    replicas: 1
  replicas: 1
  k8sVersion: "v1.34.3"
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "2"
      memory: "2Gi"
  persistence:
    enabled: false
  networking:
    clusterDomain: "cluster.local"
  hostname: custom-test.integratn.tech
  subnet: 10.0.4.0/24
  vip: 10.0.4.211
  apiPort: 443
  helmOverrides:
    controlPlane:
      proxy:
        extraSANs:
          - custom-test.integratn.tech
          - 10.0.4.211
    networking: {}
    sync:
      toHost:
        services:
          enabled: true
