---
apiVersion: platform.integratn.tech/v1alpha1
kind: VCluster
metadata:
	name: dev-test
	namespace: platform-requests
spec:
	name: dev-test
	targetNamespace: vcluster-dev-test
	preset: dev
	coredns:
		replicas: 1
	k8sVersion: "v1.34.3"
	hostname: dev-test.integratn.tech
	subnet: 10.0.4.0/24
	vip: 10.0.4.210
	apiPort: 443