apiVersion: platform.integratn.tech/v1alpha1
kind: VCluster
metadata:
  name: dev-test
  namespace: platform-requests
  annotations:
    platform.integratn.tech/reconcile-at: "2026-01-17T20:30:00Z"
spec:
  name: dev-test
  targetNamespace: vcluster-dev-test
  preset: dev
  coredns:
    replicas: 1
  k8sVersion: "v1.34.3"
  hostname: dev-test.integratn.tech
  subnet: 10.0.6.0/24
  apiPort: 443