---
apiVersion: platform.integratn.tech/v1alpha1
kind: VCluster
metadata:
  annotations:
    platform.integratn.tech/reconcile-at: "2026-01-19T15:30:00Z"
  name: dev-test
  namespace: platform-requests
spec:
  name: dev-test
  projectName: vcluster-dev-test
  targetNamespace: vcluster-dev-test
  integrations:
    argocd:
      environment: development
  preset: dev
  coredns:
    replicas: 1
  k8sVersion: "v1.34.3"
  hostname: dev-test.integratn.tech
  subnet: 10.0.4.0/24
  vip: 10.0.4.210
  apiPort: 443
  helmOverrides:
    controlPlane:
      proxy:
        extraSANs:
          - dev-test.integratn.tech
          - 10.0.4.210
