---
apiVersion: platform.integratn.tech/v1alpha1
kind: VCluster
metadata:
  annotations:
    platform.integratn.tech/reconcile-at: "2026-01-19T20:05:00Z"
  name: dev-test
  namespace: platform-requests
spec:
  name: dev-test
  projectName: vcluster-dev-test
  targetNamespace: vcluster-dev-test
  integrations:
    argocd:
      environment: development
      clusterLabels:
        enable_argocd: "true"
        enable_cert_manager: "true"
        enable_ingress_nginx: "true"
        enable_external_secrets: "true"
        enable_metrics_server: "true"
      clusterAnnotations:
        reconcile-token: "20260119200500"
  preset: dev
  coredns:
    replicas: 1
  k8sVersion: "v1.34.3"
  hostname: dev-test.integratn.tech
  subnet: 10.0.4.0/24
  vip: 10.0.4.210
  apiPort: 443
  helmOverrides:
    controlPlane:
      proxy:
        extraSANs:
          - dev-test.integratn.tech
          - 10.0.4.210
