---
apiVersion: platform.integratn.tech/v1alpha1
kind: VClusterOrchestrator
metadata:
  annotations:
    platform.integratn.tech/reconcile-at: "2026-01-19T21:30:00Z"
  name: dev-test
  namespace: platform-requests
spec:
  name: dev-test
  projectName: vcluster-dev-test
  targetNamespace: vcluster-dev-test
  vcluster:
    preset: dev
    k8sVersion: "v1.34.3"
    coredns:
      replicas: 1
    helmOverrides:
      controlPlane:
        proxy:
          extraSANs:
            - dev-test.integratn.tech
            - 10.0.4.210
  exposure:
    hostname: dev-test.integratn.tech
    subnet: 10.0.4.0/24
    vip: 10.0.4.210
    apiPort: 443
  integrations:
    certManager:
      clusterIssuerSelectorLabels:
        integratn.tech/cluster-issuer: letsencrypt-prod
    externalSecrets:
      clusterStoreSelectorLabels:
        integratn.tech/cluster-secret-store: onepassword-store
    argocd:
      environment: production
      clusterLabels:
        enable_argocd: "true"
        enable_cert_manager: "true"
        enable_ingress_nginx: "true"
        enable_external_secrets: "true"
        enable_metrics_server: "true"
      clusterAnnotations:
        reconcile-token: "20260119213000"
  argocdApplication:
    repoURL: https://charts.loft.sh
    chart: vcluster
    targetRevision: 0.30.4
