apiVersion: platform.integratn.tech/v1alpha1
kind: VClusterOrchestrator
metadata:
  name: media
  namespace: platform-requests
  annotations:
    platform.integratn.tech/reconcile-at: "2026-01-21T00:00:00Z"
spec:
  name: media
  targetNamespace: vcluster-media
  projectName: vcluster-media
  vcluster:
    preset: prod
    replicas: 3
    helmOverrides:
      controlPlane:
        service:
          spec:
            ports:
              - name: https
                port: 443
                targetPort: 8443
                protocol: TCP
              - name: https-alt
                port: 8443
                targetPort: 8443
                protocol: TCP
    resources:
      requests:
        memory: "2Gi"
      limits:
        memory: "2Gi"
    backingStore:
      etcd:
        deploy:
          enabled: true
          statefulSet:
            highAvailability:
              replicas: 3
    exportKubeConfig:
      server: https://media.integratn.tech:443
  exposure:
    hostname: media.integratn.tech
    apiPort: 443
  integrations:
    certManager:
      clusterIssuerSelectorLabels:
        integratn.tech/cluster-issuer: letsencrypt-prod
    externalSecrets:
      clusterStoreSelectorLabels:
        integratn.tech/cluster-secret-store: onepassword-store
    argocd:
      environment: production
      clusterLabels:
        enable_argocd: "true"
        enable_gateway_api_crds: "true"
        enable_nginx_gateway_fabric: "true"
        enable_cert_manager: "true"
        enable_external_secrets: "true"
          enable_external_dns: "true"
        cluster_type: "vcluster"
  argocdApplication:
    repoURL: https://charts.loft.sh
    chart: vcluster
    targetRevision: 0.30.4
