apiVersion: platform.integratn.tech/v1alpha1
kind: VClusterOrchestrator
metadata:
  name: media
  namespace: platform-requests
spec:
  name: media
  targetNamespace: vcluster-media
  projectName: vcluster-media
  vcluster:
    preset: prod
    replicas: 3
    resources:
      requests:
        memory: "2Gi"
      limits:
        memory: "2Gi"
    helmOverrides:
      controlPlane:
        backingStore:
          etcd:
            deploy:
              enabled: true
  exposure:
    hostname: media.integratn.tech
  integrations:
    certManager:
      clusterIssuerSelectorLabels:
        integratn.tech/cluster-issuer: letsencrypt-prod
    externalSecrets:
      clusterStoreSelectorLabels:
        integratn.tech/cluster-secret-store: onepassword-store
    argocd:
      environment: production
  argocdApplication:
    repoURL: https://charts.loft.sh
    chart: vcluster
    targetRevision: 0.30.4
