# Teardown in progress (commented to remove resource request)
# apiVersion: platform.integratn.tech/v1alpha1
# kind: VCluster
# metadata:
#   name: prod-test
#   namespace: platform-requests
#   annotations:
#     platform.integratn.tech/reconcile-at: "2026-01-17T20:30:00Z"
# spec:
#   name: prod-test
#   targetNamespace: vcluster-prod-test
#   preset: prod
#   coredns:
#     replicas: 1
#   replicas: 1
#   k8sVersion: "v1.34.3"
#   resources:
#     requests:
#       cpu: "500m"
#       memory: "1Gi"
#     limits:
#       cpu: "2"
#       memory: "2Gi"
#   persistence:
#     enabled: false
#   networking:
#     clusterDomain: "cluster.local"
#   hostname: prod-test.integratn.tech
#   subnet: 10.0.9.0/24
#   apiPort: 443