---
apiVersion: platform.integratn.tech/v1alpha1
kind: VCluster
metadata:
  annotations:
    platform.integratn.tech/reconcile-at: "2026-01-19T15:10:00Z"
  name: prod-test
  namespace: platform-requests
spec:
  name: prod-test
  projectName: vcluster-prod-test
  targetNamespace: vcluster-prod-test
  preset: prod
  coredns:
    replicas: 1
  replicas: 1
  k8sVersion: "v1.34.3"
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "2"
      memory: "2Gi"
  persistence:
    enabled: false
  networking:
    clusterDomain: "cluster.local"
  hostname: prod-test.integratn.tech
  subnet: 10.0.4.0/24
  vip: 10.0.4.212
  apiPort: 443
  helmOverrides:
    controlPlane:
      proxy:
        extraSANs:
          - prod-test.integratn.tech
          - 10.0.4.212
    networking: {}
