apiVersion: platform.integratn.tech/v1alpha1
kind: VClusterOrchestrator
metadata:
  name: test-cluster
  namespace: platform-requests
spec:
  name: test
  targetNamespace: vcluster-test
  projectName: vcluster-test
  vcluster:
    preset: dev
    k8sVersion: "v1.34.3"
    isolationMode: standard
    networking:
      clusterDomain: cluster.local
    coredns:
      replicas: 1
  exposure:
    hostname: test.integratn.tech
  integrations:
    certManager:
      clusterIssuerSelectorLabels:
        integratn.tech/cluster-issuer: letsencrypt-prod
    externalSecrets:
      clusterStoreSelectorLabels:
        integratn.tech/cluster-secret-store: onepassword-store
    argocd:
      environment: development
  argocdApplication:
    repoURL: https://charts.loft.sh
    chart: vcluster
    targetRevision: 0.30.4
kind: VClusterOrchestrator
