apiVersion: platform.integratn.tech/v1alpha1
kind: VClusterOrchestratorV2
metadata:
  name: vcluster-media
  namespace: platform-requests
  annotations:
    platform.integratn.tech/reconcile-at: "2026-02-08T19:56:26Z"
spec:
  name: vcluster-media
  targetNamespace: vcluster-media
  projectName: vcluster-media
  vcluster:
    preset: prod
    replicas: 3
    helmOverrides:
      controlPlane:
        distro:
          k8s:
            enabled: true
            image:
              tag: v1.34.3
        serviceMonitor:
          enabled: true
          labels:
            vcluster_name: vcluster-media
            vcluster_namespace: vcluster-media
            environment: production
            cluster_role: vcluster
        statefulSet:
          highAvailability:
            replicas: 3
          scheduling:
            podManagementPolicy: Parallel
            priorityClassName: system-cluster-critical
          imagePullPolicy: Always
          image:
            repository: loft-sh/vcluster-oss
          persistence:
            volumeClaim:
              enabled: true
              size: 10Gi
            addVolumes:
              - name: etcd-certs
                secret:
                  secretName: media-certs
            addVolumeMounts:
              - name: etcd-certs
                mountPath: /etcd-certs
                readOnly: true
          initContainers:
            - name: seed-etcd-certs
              image: busybox:1.36
              command:
                - sh
                - -c
                - |
                  cp /etcd-certs/* /pki/ && chmod 600 /pki/*.key || true
              volumeMounts:
                - name: etcd-certs
                  mountPath: /etcd-certs
                  readOnly: true
                - name: certs
                  mountPath: /pki
          resources:
            requests:
              cpu: 500m
              memory: "2Gi"
            limits:
              cpu: "2"
              memory: "2Gi"
        coredns:
          enabled: true
          deployment:
            replicas: 2
          overwriteConfig: |
            .:1053 {
              errors
              health
              ready
              kubernetes cluster.local in-addr.arpa ip6.arpa {
                pods insecure
                fallthrough in-addr.arpa ip6.arpa
                ttl 30
              }
              prometheus 0.0.0.0:9153
              forward . /etc/resolv.conf
              cache 30
              loop
              reload
              loadbalance
            }
        backingStore:
          etcd:
            deploy:
              enabled: true
              statefulSet:
                extraArgs:
                  - "--client-cert-auth=false"
                highAvailability:
                  replicas: 3
        ingress:
          enabled: false
        proxy:
          extraSANs:
            - media.integratn.tech
        service:
          enabled: true
          annotations:
            external-dns.alpha.kubernetes.io/hostname: media.integratn.tech
          spec:
            type: LoadBalancer
            ports:
              - name: https
                port: 443
                targetPort: 8443
                protocol: TCP
    resources:
      requests:
        memory: "2Gi"
      limits:
        memory: "2Gi"
    backingStore:
      etcd:
        deploy:
          enabled: true
          statefulSet:
            highAvailability:
              replicas: 3
  exposure:
    hostname: media.integratn.tech
    apiPort: 443
  integrations:
    certManager:
      clusterIssuerSelectorLabels:
        integratn.tech/cluster-issuer: letsencrypt-prod
    externalSecrets:
      clusterStoreSelectorLabels:
        integratn.tech/cluster-secret-store: onepassword-store
    argocd:
      environment: production
      clusterAnnotations:
        platform.integratn.tech/reconcile-at: "2026-02-08T05:49:15Z"
  argocdApplication:
    repoURL: https://charts.loft.sh
    chart: vcluster
    targetRevision: 0.31.0
    syncPolicy:
      automated:
        selfHeal: true
        prune: true
      syncOptions:
        - CreateNamespace=true
